  inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World2'

  outputs:
  time:
    description: 'The time we greeted you'

  runs:
  using: 'node16'
  main: 'index.js'
