name: "Install Required Libraries"
description: "Installs Java, SF CLI, SFDX-Git-Delta plugin, Salesforce Code Analyzer(sfdx scanner)."

runs:
  using: "composite"
  steps:
    - name: "Install Salesforce CLI"
      shell: bash
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
        mkdir ~/sf
        tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1
        echo "$HOME/sf/bin" >> $GITHUB_PATH
        ~/sf/bin/sf version

    - name: "Installing sfdx git delta"
      shell: bash
      run: |
        echo y | sf plugins install sfdx-git-delta
        sf plugins

    - name: "Installing java"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install default-jdk

    - name: "Installing SFDX scanner"
      shell: bash
      run: sfdx plugins:install @salesforce/sfdx-scanner
