name: check reviewer
on: push

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:

      - name: curl repo url
        run: |
        
         gh api \
         -H "Accept: application/vnd.github+json" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/subramanyam-kamath/Prod/pulls/96/requested_reviewers
        env:
             GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
             

     

           
