name: PR approved and labele

on:
  pull_request:
    types: [opened,synchronize]
  pull_request_review:
    types: [submitted]


jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ github.event.review.state }}

      - name: get approval count
        id: reviewercounts
        run: |
          echo "reviewercount=$(gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/subramanyam-kamath/Prod/pulls/${{ github.event.number }}/reviews )" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: count approval request.        
        run: |
          approval_detail='${{ steps.reviewercounts.outputs.reviewercount }}'
          echo "CURRENT_APPROVALS_COUNT=$(echo $approval_detail | jq  '[.[] | select(.state | contains("APPROVED") ) ] | length')" >> $GITHUB_OUTPUT

      - name: echo the response.
        id: approvalcount
        run: |
        
         echo  $CURRENT_APPROVALS_COUNT

    
          
