name: PR approved and label

on:
  pull_request:
    types: [opened,synchronize]
  pull_request_review:
    types: [submitted,edited]


jobs:
  check-approvals:    
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: check_approvals
        with:
          route: GET /repos/subramanyam-kamath/Prod/pulls/101/reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: test_variables
        run: |
          JSON_RESPONSE='${{ steps.check_approvals.outputs.data }}'
          CURRENT_APPROVALS_COUNT=$(echo $JSON_RESPONSE | jq -c '[.[] | select(.state | contains("APPROVED")) ] | length')
          echo $CURRENT_APPROVALS_COUNT
