name: check reviewer
on: push

jobs:
  addCommentToPr:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/github-script@v6
        with:
          script: |            
            const creator = context.payload.sender.login
            const opts = github.rest.teams.getMembershipForUserInOrg.endpoint.merge({
              org: 'subramanyam-kamath',
              team_slug: 'Teamsf',
              username: creator
            })    

      - name: echo the values        
        run: |
           echo '${{ steps.get_pr_details.outputs.data }}'
         
     
      - name: executing the curl
        id: vars
        run: |
          echo "reviewerlist= $(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/subramanyam-kamath/Prod/pulls/96/requested_reviewers | jq '.users[].login';)" >> $GITHUB_OUTPUT

      - name: echo the reviewer list.      
        run: echo ${{ steps.vars.outputs.reviewerlist }}
   :
     
