name: PR approved and labeled

on:
  pull_request:
    types: [opened,synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ github.event.review.state }}

      - name: get approval count
        id: vars2
        run: |
          echo "reviewercount=$(gh api \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/subramanyam-kamath/Prod/pulls/${{ github.event.number }}/reviews )" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: count approval request.
        run: |
          JSON_RESPONSE='${{ steps.vars2.outputs.reviewercount }}'
          
