name: Compare two branches

on:
  push:
    branches:
      - main

jobs:
  sync_folder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository
      - name: Checkout Repo 1
        uses: actions/checkout@v2

      
      - name: Copy Form Builder and Common Folder
        run: |
           npm install snyk@latest -g
           npm install snyk-to-html -g
           snyk auth  ${{secrets.SNYK_AUTH_TOKEN}}

      - name: scan the file
        run: |
         snyk code test $PWD/force-app/core-package/main/default/classes/AccountProcessor.cls
        continue-on-error: true  

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      

     
