name: Compare two branche

on:
  push:
    branches:
      - main

jobs:
  sync_folder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository
      - name: Checkout Repo 1
        uses: actions/checkout@v2

      
      - name: Copy Form Builder and Common Folder
        run: |
           npm install snyk@latest -g
           npm install snyk-to-html -g
           snyk auth  ${{secrets.SNYK_AUTH_TOKEN}}

      - name: scan the file
        run: |
         mkdir scan-reports
         snyk code test $PWD/force-app/core-package/main/default/classes/AccountProcessor.cls --json-file-output=results.json || true
         snyk-to-html -o scan-reports/results-code.html < results.json
         

      - name: Upload SARIF file
        uses: actions/upload-artifact@v3
        with:
          name: scan-report
          path: scan-reports/results-code.html

    


  salesforce-code-analyzer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: run sf scanner.
        run: sf scanner run --target ./force-app --severity-threshold 2

     
      

      

     
