name: GitHub Actions Developer Org

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - 'Feature*'
    
      

jobs:   
    validate-deployment-on-develop-org:
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0    
                
              
          
  
            - name: Read package.json
              id: package
              uses: juliangruber/read-file-action@v1
              with:
               path: ./.sgdignore
            - name: Test
              run: echo "Read_File_Content=${{ steps.package.outputs.content }}" >> $GITHUB_ENV
            - name: testrun
              run: echo ${{env.Read_File_Content}}
              
            - name: Get version
              id: vars
              run: echo ::set-output name=version::$(cat package.json)
            - name: Test output 
              run: echo ${{ steps.vars.outputs.version }}
                
            
