name: GitHub Actions Developer Org

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - 'Feature*'
    
      

jobs:   
    validate-deployment-on-develop-org:
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0    
                
              
          
  
        
              
            - name: Get version
              id: vars
              run: echo ::set-output name=version::$(cat TestClass.txt)
            - name: Test output 
              run: echo ${{ steps.vars.outputs.version }}
                
            
