name: Executing GitHub Actions on Develop
run-name: ${{ github.actor }} is validating the Deployment on the ${{github.ref_name}}
on:
  push:
    branches:
      - "main"
    paths:
      - 'automations/**'
      
jobs:
    identify_and_store_deleted_files:
     runs-on: ubuntu-latest
     steps:
       - uses: devforce/setup-node@v3.5.1
         with:
          node-version: "18"
    
     
          
       - name: Checkout code
       - uses: actions/checkout@v2
         with:
                fetch-depth: 0 
                
       
       - name: Deploy destructive changes
         run: sf project deploy start --dry-run --source-dir deleted_files --test-level NoTestRun
