name: Executing GitHub Actions on Develop
run-name: ${{ github.actor }} is validating the Deployment on the ${{github.ref_name}}
on:
  push:
    branches:
      - "main"
    
      
jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest        
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
    
         
          
      
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                 fetch-depth: 0

            - name: Identify Deleted Files
              id: deleted-files
              run: |
                # Capture deleted files into a variables
                deleted_files=$(git diff --name-only --diff-filter=A)
                # Create a directory to store deleted files
                mkdir ~/added-files
                # Iterate over deleted files and move them to the directory
                for file in $deleted_files; do
                mv $file added_files/
                echo "Deleted files: $deleted_files"

            
