name: Executing GitHub Actions on UAT Environment
run-name: ${{ github.actor }} is validating the Deployment on the ${{github.ref_name}}
on:
   workflow_dispatch: 

       inputs:
         PreviousVersionBranchName:
          type: string
          description: 'Define previous version of release branch'     
          required: true

         LatestVersionBranchName:
          type: string
          description: 'Define latest version of release branch'
          required: true

         UatBrancName:
           type: string
           description: 'Define name of UAT Branch'
           required: true
        

env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

    
      
jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest        
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
    
         
            - name: Get date value and append it to branch name
              run: |
                 echo "RELEASE_DATE=$(date +'%Y-%m-%dT%H-%M-%S')" >> ${GITHUB_ENV}

            - name: Check out Previous release version.
              uses: actions/checkout@v3
              with:
               repository: subramanyam-kamath/Prod               
               ref: ${{github.event.inputs.PreviousVersionBranchName}}

            - name: Copy the metadata from previous release version
              run: |
                 mkdir -p tempfolder              
                 cp -r force-app tempfolder

            - name: Identify the newly added components between previous version & current version
              run: |
               git fetch --all
               echo $(git diff --name-status --diff-filter=A origin/${{github.event.inputs.PreviousVersionBranchName}}..origin/${{github.event.inputs.LatestVersionBranchName}}) >> newlyadded.txt
               echo $(git diff --name-status --diff-filter=A origin/${{github.event.inputs.PreviousVersionBranchName}}..origin/${{github.event.inputs.LatestVersionBranchName}} | sed 's/^.//') >> textfile.txt  
                 
            - name: Delete the newly added files.
              run: | 
                cat newlyadded.txt                
                cat textfile.txt | while IFS= read -r line ;
                do  
                cd tempfolder
                rm -f tempfolder/$line; 
                done
                
            - name: create new branch
              run: |
               ls tempfolder/force-app/main/default/classes
               git fetch --all
               git checkout -b destructive/${{env.RELEASE_DATE}}  origin/${{github.event.inputs.LatestVersionBranchName}}

            
            - name:  sync the changes from previous version to current branch
              run: cp -r tempfolder/force-app/. force-app                        
                              
                   

            - name: git config set
              run: |
                  git config --global user.email "skamath@salesforce.com"
                  git config --global user.name "skamathsf"

           
            -  name: Push & Commit file               
               run: | 
                git add force-app  
                git commit -m "added destructive folder"
                cat textfile.txt | while IFS= read -r line ;
                do                  
                git rm $line; 
                done
                git commit -m'deleted files'
                

            - name: Push file to remote repository.
              run: |
               git push origin destructive/${{env.RELEASE_DATE}}

            - name: "Install Salesforce CLI"
              run: |
               wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
               mkdir ~/sfdx
               tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
               echo "$HOME/sfdx/bin" >> $GITHUB_PATH
               ~/sfdx/bin/sfdx version
          
            - name: "Installing sfdx git delta"
              run: |
               echo y | sfdx plugins:install sfdx-git-delta
               sfdx plugins    
                 
            - name: "Installing java"
              run: |
                sudo apt-get update
                sudo apt install default-jdk

            - name: Generate the package.xml for delta files
              run: |
                mkdir delta
                sfdx sgd:source:delta --from origin/feature/version2 --source force-app --output "./delta" --ignore-whitespace -d -i .sgdignore
                echo "--- package.xml generated with added and modified metadata ---"                
                cat delta/package/package.xml
                cat delta/destructiveChanges/destructiveChanges.xml
                sfdx sgd:source:delta --from origin/feature/version2 --source force-app --output "."  -i .sgdignore
                echo "--- destructive.xml generated with added and modified metadata ---"
                cat destructiveChanges/destructiveChanges.xml
                
                
            
