name: Executing GitHub Actions on Develop
run-name: ${{ github.actor }} is validating the Deployment on the ${{github.ref_name}}
on:
   pull_request:
        types: [opened,synchronize]
        branches:
            - "main"
    
      
jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest        
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
    
         
          
      
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                 fetch-depth: 0

            - name: Identify Deleted Files
              id: deleted-files
              run: |
               git whatchanged --diff-filter=A feature/**...main
                echo "Deleted files: $deleted_files"

            
