name: Executing GitHub Actions on Develop
run-name: ${{ github.actor }} is validating the Deployment on the ${{github.ref_name}}
on:
   pull_request:
        types: [opened,synchronize]
        branches:
            - "main"


env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

    
      
jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest        
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
    
         
          
      
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                 fetch-depth: 0

            - name: Identify the newly added components
              run: |
               echo $(git diff --name-status --diff-filter=A origin/main...origin/feature/testaddedfile) >> newlyadded.txt
               git diff --name-status origin/feature/testaddedfile..origin/main             
               
                

            - name: echo the newly added classes
              run: |
               cat newlyadded.txt
               mkdir manualdestructivepackage
               cat newlyadded.txt | while IFS= read -r line ; do mv $line manualdestructivepackage; done
               
            - name: list the files
              run: ls manualdestructivepackage            

            - name: git config set
              run: |
                  git config --global user.email "skamath@salesforce.com"
                  git config --global user.name "skamathsf"

            - name: checkout the current branch
              run: git checkout -b feature/testaddedfile

            -  name: Push & Commit file               
               run: | 
                git add manualdestructivepackage
                git commit -m "added destructive folder"

            - name: Push file to remote repository.
              run: |
               git push origin feature/testaddedfile

            - name: "Install Salesforce CLI"
              run: |
               wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
               mkdir ~/sfdx
               tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
               echo "$HOME/sfdx/bin" >> $GITHUB_PATH
               ~/sfdx/bin/sfdx version
          
            - name: "Installing sfdx git delta"
              run: |
               echo y | sfdx plugins:install sfdx-git-delta
               sfdx plugins    
                 
            - name: "Installing java"
              run: |
                sudo apt-get update
                sudo apt install default-jdk

            - name: Generate the package.xml for delta files
              run: |
                mkdir delta
                sfdx sgd:source:delta --from origin/main --source manualdestructivepackage --output "./delta" --ignore-whitespace -d -i .sgdignore
                echo "--- package.xml generated with added and modified metadata ---"
                git tag v1.0.0
                
                cd delta/package
                mv package.xml destructive.xml
                cat destructive.xml
            
