name: Executing GitHub Actions on Develop
run-name: ${{ github.actor }} is validating the Deployment on the ${{github.ref_name}}
on:
  workflow_dispatch:
  push:
env:
  env_text: ${{ vars.TEXT }}
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.env_text == '' }}
        run: |
          echo "Empty text"
      - if: ${{ env.env_text != '' }}
        run: |
          echo "Text: '$env_text'"
