name: Checkmarx OSA Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9


      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run Salesforce Code Analyzer
        run: echo $(sf scanner rule list --language apex,javascript) >> apexruleset.csv

      - name: commit the file.
        run: | 
            git config --global user.email "subramanyam.kamath@gmail.com"
            git config --global user.name "subramanyam-kamath"
            git add .
            git commit -m "This is our commit message"
            git push origin main

      - name: Get describe rule name
        run: sf scanner rule describe --rulename ApexAssertionsShouldIncludeMessage