run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
   branches:
      - "feature/**"
   
env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch       
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0              
      

      - name: Get diff file names
        id: vars
        run: |
        
          echo $(gh pr diff --name-only) >> deltaclass.txt
          cat deltaclass.txt |  tr ' ' '\n'| egrep "force-app/main/default/classes/" |  awk  -F/ '{print $NF}' |   paste -sd " " |   sed 's/.cls//g' | sed 's/.trigger//g'  |sed 's/-meta.xml//g'   | sed -e "s/ /,/g"   >> deltaclass2.txt
          echo "testclass2=$(cat deltaclass2.txt )" >> $GITHUB_OUTPUT

      - name: Get diff file names
        id: vars3
        run: |
          cat deltaclass.txt |  tr ' ' '\n' |   awk  -F/ '{print $NF}' |   paste -sd " " |   sed 's/.cls//g' | sed 's/.trigger//g'  |sed 's/-meta.xml//g'   | sed -e "s/ /,/g"   >> deltaclass3.txt
          echo "testclass5=$(cat deltaclass3.txt )" >> $GITHUB_OUTPUT


      - name: print the classes
        id: vars2
        run: |
         echo ${{ steps.vars.outputs.testclass2 }} |  echo ${{ steps.vars3.outputs.testclass5 }}  >> ninja.txt
        
        
      - name: Use env variable
        run: |
           
           cat ninja.txt
                  
