run-name: ${{ github.actor }} is testing out GitHub Actions 
on: 
  push:
   
   


jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch       
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'  

      

      - name: create new branch
        run: git checkout -b feature/copyofmain origin/main	
          

        
      - name: Checking for difference between drm common metadata & current repo.
        run: |
          mkdir -p tempfolder 
          find force-app -type f -print0 | xargs -0 mv -t tempfolder

      - name: techo the folder
        run: ls tempfolder

      - name: git config set
        run: |
          git config --global user.email "subramanyam.kamath@gmail.com"
          git config --global user.name "subramanyam-kamath"

      - name: Push & Commit file        
        run: | 
           git add tempfolder
           git commit -m "added raw files"

      - name: Push file to remote repository.        
        run: |
          git push origin feature/copyofmain

      
           
          
 
           
