run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
   branches:
      - "feature/**"
   


jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch       
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0              
      

      - name: Get diff file names
        run: echo $(git diff-tree --no-commit-id --name-only -r ..origin/main force-app/main/default/classes/) >> deltaclass.txt

      - name: formatize class names
        id: vars
        run: |
         
         cat deltaclass.txt |  sed 's/^/'"'"'/' |  sed  's/$/'"'"'/' | sed -e "s/ /','/g"   >> Tobemerged.txt  
         echo "exception= $(cat Tobemerged.txt)" >> $GITHUB_OUTPUT

      - name: echo the classes
        run: |
        
         echo ${{ steps.vars.outputs.exception }}
         cat deltaclass.txt 
         cat Tobemerged.txt  
