run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
   branches:
      - "feature/**"
   
env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch       
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0              
      

      - name: Get diff file names
        id: vars
        run: |
        
          echo $(gh pr diff --name-only) >> deltaclass.txt
          cat deltaclass.txt |  tr ' ' '\n'| egrep "force-app/main/default/classes/" |  awk  -F/ '{print $NF}' | uniq|  paste -sd " " |   sed 's/.cls//g' | sed 's/.trigger//g'  |sed 's/-meta.xml//g' | sed 's/^/'"'"'/' |  sed  's/$/'"'"'/' | sed -e "s/ /','/g"   >> deltaclass2.txt
          


      - name: print the classes
        run: |
         cat deltaclass2.txt
                  
