run-name: ${{ github.actor }} is testing out GitHub Action🚀
on: 
  push:
   branches:
      - "destructive/**"
   


jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch       
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0              
      

      - name: Get diff file names
        id: vars
        run: echo $( git diff --name-only --diff-filter=A  origin/main..${{github.ref_name}} force-app/main/default/classes/) >> deltaclass.txt

      - name: print the classes
        run: cat deltaclass.txt

      - name: create new directory
        run: mkdir -p  destructive

      - name: copy the files to directory
        run: cp --parents force-app/main/default/classes/NewClassadded.cls force-app/main/default/classes/NewClassadded.cls-meta.xml force-app/main/default/classes/NoDiffClass.cls force-app/main/default/classes/NoDiffClass.cls-meta.xml destructive

      - name: git config set
        if: ${{always()}}
        run: |
                git config --global user.email "subramanyam.kamath@gmail.com"
                git config --global user.name "subramanyam-kamath" 
              

      - name: Push & Commit file    
        if: ${{always()}}
        run: | 
                   git pull origin ${{github.ref_name}}
                   git  add destructive                
                   git commit -m "added destructive file"


      - name: Push file to remote repository. 
        if: ${{always()}}
        run: |
              
               git push origin ${{github.ref_name}}
             
            

