run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
   
   


jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch       
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0            

        
      - name: Checking for difference between drm common metadata & current repo.
        run: |
          mkdir -p tempfolder 
          find ~/force-app/ -type f -print0 | xargs -0 mv -t ~/tempfolder

      - name: techo the folder
        run: ls tempfolder


          
 
           
