name: GitHub Actions Developer Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
   schedule:
    - cron: '5 * * * *'
   workflow_dispatch: 

jobs:   
    validate-deployment-on-develop-org:        
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            
            - name: Get date value and append it to branch name
              run: |
                 echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
            
            - name: create new branch
              run: git checkout -b Release/${{env.RELEASE_DATE}}  origin/main	

            - name: publish to github
              run: git push origin Release/${{env.RELEASE_DATE}}
            
