name: GitHub Actions Developer Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - 'feature/**'
    paths:
      - 'force-app/**'

jobs:   
    validate-deployment-on-develop-org:        
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            

            - name: 'Read commit Body'
              env:
                 PR_BODY: ${{ github.event.head_commit.message }}

             
              run: |
                  echo $PR_BODY > ./pr_body.txt
                  node ./parsePR.js              
                  TESTS=$(cat testsToRun.txt)       
                  echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
                  
            
            - name: Install required libraries
              run: ./.github/actions/install-libraries
            
            - name: Decrypt the server.key.enc file & store inside assets folder
              run: openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
              

            
            - name: Authenticate Salesforce ORG
              run: |
                sfdx force:auth:jwt:grant --clientid ${{ secrets.HUB_CONSUMER_KEY }} --jwtkeyfile ${{ secrets.JWT_KEY_FILE }} --username ${{ secrets.HUB_USER_NAME }} --setdefaultdevhubusername -a HubOrg
                
                
            - name: Generate the package.xml for delta files
              run: |
                mkdir delta
                sfdx sgd:source:delta --to ${{github.ref}} --from origin/QA-Org --output "./delta" --ignore-whitespace -d -i .sgdignore
                echo "--- package.xml generated with added and modified metadata ---"
                cat delta/package/package.xml
                
            - name: 'Check-only full deploy changes - run specified tests'
              if: ${{ github.event.head_commit.message == 'DeltaDeploy' }}
              run: |
                  echo ${{github.event.head_commit.message}}
                   sfdx force:source:deploy -x delta/package/package.xml -c --testlevel NoTestRun  -u HubOrg
                 # sfdx force:source:deploy -x delta/package/package.xml -c --testlevel RunSpecifiedTests --runtests ${{github.event.pull_request.body}}  -u HubOrg

            
            - name: 'Check-only deploy delta changes - run all tests'
              if: ${{ github.event.head_commit.message == 'FullDeploy' }}
              run: |
                  sfdx force:source:deploy -p force-app -c --testlevel RunLocalTests -u HubOrg

            
