run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch: 


env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch

     outputs:
         csv_file_in_repo: ${{steps.vars.outputs.test}}

        
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
                
      - name: Get CSV file names
        id: vars
        run: echo "test= $(find files/ -name "*.csv" | sed 's/files//g' | sed 's/[/]//g' |paste -sd",") "  >>  "$GITHUB_OUTPUT"

      

        

    job2:
      runs-on: ubuntu-latest
      needs: Getting-the-export-files
      steps:
      - env:
          OUTPUT1: ${{needs.Getting-the-export-files.outputs.csv_file_in_repo}}
          
        run: echo "$OUTPUT1"

  


            
