run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch: 


env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
    Getting-the-export-files:
     runs-on: ubuntu-latest
     environment: QA-Branch

     outputs:
         csv_file_in_repo: ${{steps.vars.outputs.csv_file_in_repo}}

        
     
     steps:            
      - uses: actions/setup-node@v3
        with:
         node-version: '14'

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
                
      - name: Get CSV file names
        id: vars
        run: echo ::set-output name=version::$(find files/ -name "*.csv")

      - name: Print file names
        run: echo "test_classes_in_repo= ${{ steps.vars.outputs.version }}" >> $GITHUB_ENV

        

      
           

  


            
