name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened,synchronize]
    branches:
      - "QA-Org"
    paths:
      - 'force-app/**'

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            

                          
            
            - name: 'Install Salesforce CLI'
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                  mkdir ~/sfdx
                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                  ~/sfdx/bin/sfdx version

           
            - name: 'Installing sfdx git delta'
              run: | 
                  echo y | sfdx plugins:install sfdx-git-delta
                  sfdx plugins 

            
            - name: 'Installing java'
              run: |
                sudo apt-get update
                sudo apt install default-jdk

            
            - name: 'Installing SFDX scanner'
              run: sfdx plugins:install @salesforce/sfdx-scanner

            
            - name: Decrypt the server.key.enc file & store inside assets folder
              run: openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTION_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
              

            
            - name: Authenticate Salesforce ORG
              run: |
                sfdx force:auth:jwt:grant --clientid ${{ secrets.HUB_CONSUMER_KEY }} --jwtkeyfile ${{ secrets.JWT_KEY_FILE }} --username ${{ secrets.HUB_USER_NAME }} --setdefaultdevhubusername -a HubOrg

            - name: Create scratch org
              run: |
                 sf org create scratch --target-dev-hub HubOrg -d -f config/project-scratch-def.json -a trailheadacademy-org
                             
            - name: Generate the package.xml for delta files
              run: |
                mkdir delta

                sfdx sgd:source:delta  --from origin/QA-Org --output "./delta" --ignore-whitespace -d -i .sgdignore

                echo "--- package.xml generated with added and modified metadata ---"
                cat delta/package/package.xml
            

            - name: Get role id & store in the variable.
              id: varss
              run: echo ::set-output name=version::$(sf data query --query "SELECT Id FROM UserRole where Name='ceo'" --result-format csv )

            - name: Passing the Role id to Env variable
              run: echo "role_id= ${{ steps.varss.outputs.version }}" > roleid.txt

            - name: print role id1 file
              run: cat roleid.txt

            - name: remove id name from the file
              run: sed -i 's/role_id= Id//g' roleid.txt

            - name: print role id file
              run: cat roleid.txt

            - name: print role file
              run: |
               value=$(<roleid.txt)
               echo "$value"

            - name: set env variable result
              run: |
              env:
                Role_id: |
                -value : $(<roleid.txt)

            - name: print env variable
              run: echo ${{env.Role_id}}

            - name: Assign role to scratch org Admin
              run:  |
               sf data update record --sobject User --where "email='skamath@salesforce.com'" --values "UserRoleid=1234556677"
            
            - name: 'Check-only full deploy changes - run specified tests'
              if: ${{ github.event.pull_request.body!= 'DeploytoQAorg' }}
              run: |
                  echo ${{github.event.pull_request.body}}
                  sfdx force:source:deploy -x delta/package/package.xml -c --testlevel RunLocalTests -u trailheadacademy-org
                
            
            - name: 'Check-only deploy delta changes - run all tests'
              if: ${{ github.event.pull_request.body == 'DeploytoQAorg' }}
              run: |
                  sfdx force:source:deploy -x delta/package/package.xml -c --testlevel RunLocalTests -u trailheadacademy-org

            
