name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - "main"
   

env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            

            
                 
            - name: Trimming the characters.
              id: vars68
              run: |
               cat apexclassnames.txt |  sed 's/^/'"'"'/' |  sed  's/$/'"'"'/' | paste -sd "," | sed 's/\/t//g' | sed 's/[[:blank:]]//g'   > sortedfile.txt
               echo "exception= $(cat apexclassnames.txt |  sed 's/^/'"'"'/' |  sed  's/$/'"'"'/' | paste -sd "," | sed 's/\/t//g' | sed 's/[[:blank:]]//g' )"  >  $GITHUB_OUTPUT
               cat sortedfile.txt

            
            - name: run the local file.
              run: |      
                     echo "$(  sed -i 's/yourtexthere/testme/g' scripts/apex/hello.apex )" >> runtestclass.apex

            - name: cat the file
              run: cat runtestclass.apex
                  
           
                  
                  
            
            
            - name: Authenticate Salesforce ORG
              run: |
                sfdx force:auth:jwt:grant --clientid ${{ secrets.HUB_CONSUMER_KEY }} --jwtkeyfile ${{ secrets.JWT_KEY_FILE }} --username ${{ secrets.HUB_USER_NAME }} --setdefaultdevhubusername -a HubOrg

          
