name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - "main"
   

env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            

            
                 
            - name: Trimming the characters.
              id: vars68
              run: |
               cat apexclassnames.txt |  sed 's/^/'"'"'/' |  sed  's/$/'"'"'/' | paste -sd "," | sed 's/\/t//g' | sed 's/[[:blank:]]//g'   > sortedfile.txt
               echo "exception= $(cat apexclassnames.txt |  sed 's/^/'"'"'/' |  sed  's/$/'"'"'/' | paste -sd "," | sed 's/\/t//g' | sed 's/[[:blank:]]//g' )"  >  $GITHUB_OUTPUT
               cat sortedfile.txt
               cat scripts/apex/hello.apex

            
            - name: run the local file.
              run: |      
                    cat scripts/apex/hello.apex  > classfile.txt

            - name: cat the file
              run:  cat classfile.txt | sed -i 's/yourtexthere/testme/g' classfile.txt      > testfile.txt

            - name: echo the test file
              run: cat testfile.txt
                  
                  
            
            
            
