name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions23 🚀
on: 
  pull_request:
    types: [opened,synchronize]
    branches:
      - "QA-Org"
    paths:
      - 'force-app/**'

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            

            - name: 'Read commit Body'
              run: |
                 echo ::set-output name=version:: ($grep –e "Lines"  codecoverage.txt)
                 echo "test_classes_in_repo= ${{ steps.vars.outputs.version }}" >> $GITHUB_ENV
