name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened,synchronize]
    branches:
      - "QA-Org"
    paths:
      - 'force-app/**'

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            - name: remove id name from the file
              id: vars
              run:  echo ::set-output name=version::sed -i 's/Id//g' roleid.txt

            - name: set the output to variable
              run: echo "test_classes_in_repo= ${{ steps.vars.outputs.version }}" >> $GITHUB_ENV

            - name: Name of the apex test classes
              run: echo ${{env.test_classes_in_repo}}
              
              
            

            - name: print role file
              run: cat roleid.txt

            - name: gerp command to exclude Id string from CSV format and capture only Role id
              id: vars2
              run: echo ::set-output name=version::$(grep  "foo" roleid.txt )

            - name: assign local variable to environment
              run: echo "test_classes_in_repo= ${{ steps.vars2.outputs.version }}" >> $GITHUB_ENV

            - name: Id of the Role in environment variable
              run: echo ${{env.test_classes_in_repo}}

          
