name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened,synchronize]
    branches:
      - "QA-Org"
    paths:
      - 'force-app/**'

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
            

            - name: Get Apex test class names
              id: vars
              run: echo ::set-output name=version::$(grep -i "Lines" codecoverate.txt |cut -c 5-22  )
            - name: Passing the test class names to Env variable
              run: echo "test_classes_in_repo= ${{ steps.vars.outputs.version }}" >> $GITHUB_ENV
            - name: Name of the apex test classes
              run: echo ${{env.test_classes_in_repo}}


            - name: 'Print Test file'
              run: |
                 cat codecoverate.txt

            - name: 'Print variable info'
              run: |
                   echo ${{env.test_classes_in_repo}}

