name: GitHub Actions QA Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - "main"
   

env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN}} 
   day: Monday

jobs:   
    validate-deployment-on-QA-org:        
        runs-on: ubuntu-latest
        environment: QA-Branch
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'           
              
                
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0    

            - name: run the test classes.
              run: |
        
                 mkdir -p  tempfolder
                 cp -r apexclassnames.txt tempfolder

            - name: run the local file.
              id: vars
              run: | 
              
                 ls -1 tempfolder 
                 sed -i 's/yourtexthere/${{env.day}}/g'  tempfolder/apexclassnames.txt
                 echo "testfile=$(cat tempfolder/apexclassnames.txt | 's/^/"/;s/$/"/' | sed 's/^/'"'"'/' |  sed  's/$/'"'"'/'| paste -sd ",")" >> $GITHUB_OUTPUT 

            
            - name: echo the variable
              run: echo ${{steps.vars.outputs.testfile}}
