name: Update module
on:
  workflow_call:
jobs:
  update:
    runs-on: ubuntu-latest
         
    steps:         
      - run: |
           git submodule update --init --recursive --checkout -f --remote -- "Merge"
           git config --global user.name "GitHub Action"
           git config --global user.email "noreply@github.com"
           git commit 
           git push
