name: Update module
on:
  workflow_dispatch:
  repository_dispatch:
   workflow_call:
    types: update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: checkout the branch
        run: git checkout -b Modulechange  
    
      - name: Update module
        run: |
          git submodule update --init --recursive --checkout -f --remote -- "Merge"
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "Updated with latest commit"          
          git config --global pull. ff only
          git push  -u origin Modulechange
