name: GitHub Actions Developer Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
   workflow_dispatch: 

jobs:   
    validate-deployment-on-develop-org:        
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       

           
            - name: Read the testClassnames,Exceptional class & pass it to output variable.
              run: |  
               echo $(cat apexclassnames.txt  | tr " " "\n"    ) >> testclasslist.txt
               echo $(echo "/path/to/file /path/to/file2 /path/to/file3 /path/to/file4 /path/to/file5" \ | tr " " "\n") >> pathtofile.txt

            - name: echo test classes
              run: cat pathtofile.txt
