name: GitHub Actions Developer Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
   workflow_dispatch: 

jobs:   
    validate-deployment-on-develop-org:        
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       
                
            - name: create new branch
              run: echo $(find . -type f -iregex '.*\.cls' -not -iregex '.*node\_modules.*' -exec grep -Eil --color '@IsTest' {} \; | grep -oE '[^/]*$' | sed 's/.cls//g' | sort | uniq | paste -sd " " -) >> testClassname.txt
               
            - name: Defining a new Environment Variable
              run: |                          
               {
               echo 'JSON_RESPONSE<<EOF'
               cat testClassname.txt | tr ' ' '\n' 
               echo EOF
                 } >> "$GITHUB_ENV"

            - name: echo test classes
              run: |
                 echo $( echo ${{env.JSON_RESPONSE}}) >> test.txt

            - name: echo test file
              run: cat test.txt apexclassnames.txt > groupedclasses.txt

            - name: echo teh goruped file
              run: cat groupedclasses.txt
