name: GitHub Actions Developer Org
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
   workflow_dispatch: 

jobs:   
    validate-deployment-on-develop-org:        
        runs-on: ubuntu-latest
        environment: developer
        steps:            
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0       

            
            - name: Defining a new Environment Variable
              run: |                          
               {
               echo 'JSON_RESPONSE<<EOF'
               cat apexclassnames.txt | tr ' ' '\n' 
               echo EOF
                 } >> "$GITHUB_ENV"

            - name: echo test classes
              run: |
                echo "JSON_RESPONSE" > text.txt
